### ISSUE TITLE
Some ideas for you to consider

### ISSUE THREAD

**Issue by David-Else** [chmaha/DebianProAudio#1]
Thanks for writing this guide, I have some ideas that might improve it:

- As it is called DebianProAudio, drop all the Ubuntu references
- Make the minimum version of Debian 12, then you can assume that Pipewire is default and get rid of anything that does not directly relate to that
- In https://github.com/chmaha/DebianProAudio#4-add-user-to-audio-group-and-configure-realtime-privileges you are assuming either not using Pipewire or an old Pipewire. In modern versions this is done for you, the file `/etc/security/limits.d/95-pipewire.conf` is created automatically:

```sh
# Default limits for users of pipewire
@pipewire - rtprio 95
@pipewire - nice -19
@pipewire - memlock 4194304
```
You just need to create the pipewire group and add your user to it.

Anyway, just a few thoughts. I have done a bit of work documenting some of this, but it is not ideal or complete: https://github.com/David-Else/developer-workstation-setup-script-debian#audio

**Comment by chmaha** [comment]
Yes to the first two points (aside from the fact that Ubuntu is, of course, derived from Debian so will still be of use in many regards). As for the pipewire group, I believe this was already created on my Debian 12 (at least I don't remember creating it!). I don't think it matters much whether you create your own audio.conf for an audio group or via installation of JACK2 or add yourself to the pipewire group. Probably one or the other though? Then the other question is whether pipewire is only default on GNOME? The documentation seems to suggest so.

Consider the guide in initial commit stage. I've not announced it anywhere as yet and, indeed, might hide it for the time being.

**Comment by David-Else** [comment]
> Then the other question is whether pipewire is only default on GNOME? The documentation seems to suggest so.

I am pretty sure Pipewire is only default on Gnome, but I am not certain. I think the vast majority of people use Gnome, so you could just add an aside saying if you don't have Pipewire installed how to do it... if you thought it was worth the bother.

> As for the pipewire group, I believe this was already created on my Debian 12 (at least I don't remember creating it!).

My Debian 12 install never had a pipewire group, I did a fresh install using the Debian 12 dvd media on a USB stick (not net install) and left everything at default regarding what to install. I added this in my installer:

```yml
    # =========================================================================
    # Add user to groups
    # =========================================================================
    - name: Create pipewire group
      become: true
      ansible.builtin.group:
        name: pipewire

    - name: Add user to the pipewire group
      become: true
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: pipewire
        append: true
```
> own audio.conf for an audio group or via installation of JACK2

I don't know anything about using the original JACK, only the new Pipewire JACK.
